### ISSUE TITLE
Need to enable Audit in Tenant

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/SC-5003_Information-protection-and-Data-Loss-Prevention#4]
# Module: 00
#### Step: 08

Description of issue
Error is thrown when trying to create the policy because Auditing is not enabled in the lab tenant.
Is this a lab setup error, or do we need to add the steps for the student?

**Comment by riswinto** [comment]
Thank you for bringing this to my attention. These labs have been updated to reflect the new Microsoft Purview portal, and part of this update includes a lab to enable Audit on the tenant.
