### ISSUE TITLE
small error and some updates to the UI

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/SC-5003_Information-protection-and-Data-Loss-Prevention#5]
# Module: 00
#### Step: 12

Description of issue
Student is instructed in the third bullet to select "Sensitive info types", but the next bullet is using Trainable classifiers.
Seventh bullet: "Restrict" is now "Restrict access"
Ninth bullet: "or email notification" has been added

And in Step 14: "Run the policy in test mode" is now: "Run the policy in simulation mode".
![Screenshot-actions](https://github.com/user-attachments/assets/1507e042-3697-4aa6-b297-b95936e4889d)
![Screenshot-simulation mode](https://github.com/user-attachments/assets/9e91831b-ebed-43e1-944d-1fcec56d9eaa)
![Screenshot-Notifications](https://github.com/user-attachments/assets/6a5750ce-6ee2-4a8d-aac4-786016ca51d1)

**Comment by ITBlandMCT** [comment]
Additional problem: Ex 2, Task 3, Step 1 is missing "Select "Publish labels".

**Comment by riswinto** [comment]
Thank you for bringing this to my attention. These labs have been updated to reflect the new Microsoft Purview portal. These errors have been addressed as part of the update.
